Code/app/models/Rank.py
from app import db


class Rank(db.Model):
    __tablename__ = 'rank'
    place_id = db.Column(db.String(50), db.ForeignKey('school.place_id'), primary_key=True)
    name = db.Column(db.String(255), nullable=False, primary_key=True)
    official_school_name = db.Column(db.String(255))
    rank = db.Column(db.Integer)
    p_rank = db.Column(db.Integer)
    gender_type = db.Column(db.String(50))
    at_university = db.Column(db.Float(10))  # ?
    at_third_level = db.Column(db.Float)
    boy = db.Column(db.Integer)
    girl = db.Column(db.Integer)
    stu_tea_ratio = db.Column(db.Float(10))  # ?
    photo = db.Column(db.String(255))

Code/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField,
                     SubmitField,)
from wtforms.validators import (DataRequired,
                                Length,)


class SearchForm(FlaskForm):
    search = StringField('', validators=[Length(0, 255), DataRequired() ],render_kw={"placeholder": "Please input school name or address here"})
    lat = StringField('')
    lng = StringField('')

    submit = SubmitField('submit')

Code/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

Code/app/main/views.py
from .. import db
from . import main
from ..models.School import School
from ..models.Pro2015 import Pro2015
from ..models.Pro2016 import Pro2016
from ..models.Pro2017 import Pro2017
from ..models.Rank import Rank
from ..models.User import User
from flask import (render_template,
                   abort,
                   request, redirect,
                   url_for,
                   jsonify,)  # json conversion
from flask_login import current_user
from .forms import SearchForm
from ..models.User_operation import Comment

current_location = None
user_db = None


@main.route('/distance_computing/<geolocation>/<city>', methods=['GET', 'POST'])
def distance_computing(geolocation, city):
    """
    This function is used for distance computing and sorting
    :param geolocation: the coordinate of the place
    :param city: The city where the place is located
    :return: Sorted school list (JSON)
    """
    # process geolocation data
    geo_split = geolocation.split(',')
    global current_location
    current_location = geo_split

    if city == 'Ireland':
        school_list = db.session.query(School, Pro2017, Rank).outerjoin(Pro2017) \
            .outerjoin(Rank).all()
    else:
        school_list = db.session.query(School, Pro2017, Rank).outerjoin(Pro2017) \
            .outerjoin(Rank).filter(School.county == city)

    page_count = school_list.count() // 6

    # restrict the page number
    if page_count > 5:
        page_count = 5

    schools = school_list.all()
    schools_list = list(schools)

    # compute distance for each school
    for school in schools_list:
        distance_computing = School.distance_calculator(float(school[0].lat), float(school[0].lng),
                                                        float(geo_split[0]), float(geo_split[1]))
        school = list(school)
        school[0].distance = distance_computing

    # sort the data by distance
    schools_list.sort(key=lambda x: x[0].distance)

    # convert data to JSON format
    data = School.make_json(schools_list)
    if len(data) > 30:
        json_list_limitation = data[0:30]
    else:
        json_list_limitation = data

    return jsonify({'result': json_list_limitation, 'page_count': page_count})


@main.route('/', methods=['GET', 'POST'])
def index():
    """
    This function is for main page, this page includes search box(Web Form) and school information display
    :return: render the main page first, when user click submit button, redirect to the result page
    """
    global user_db
    global current_location
    user_db = db.session.query(School, Rank, Pro2017).outerjoin(Rank).outerjoin(Pro2017)

    # create the account for anonymous user
    if User.current_anonymous_user():
        pass
    else:
        User.create_anonymous()

    # search engine
    form = SearchForm()
    if form.validate_on_submit():
        # get the user input place's latitude and longitude
        if form.lat.data == '' and form.lng.data == '':
            if 'ireland' not in form.search.data.lower():
                keyword = form.search.data + ' ' + 'Ireland'
            else:
                keyword = form.search.data

            # get the coordination of the place from google maps
            # sometimes, it cannot get the result due to network issue, so try to get it five time
            signal = True
            count = 0
            while signal:
                input_coordination = User.get_coordination(keyword)
                count = count + 1
                if len(input_coordination) != 0 or count == 5:
                    signal = False
                    break
            if len(input_coordination) == 0:
                input_coordination = 'unknown'

        elif form.lat.data != '' and form.lng.data != '':
            input_coordination = [form.lat.data, form.lng.data]
        else:
            input_coordination = 'unknown'
        # process input_coodination
        if input_coordination != 'unknown':
            geolocation = str(input_coordination[0]) + "," + str(input_coordination[1])
        else:
            geolocation = "search_location"

        # GET THE NUMBER IN STRING, process input keyword like Dublin1 and Dublin 1(has space and no space)
        user_input = form.search.data
        input_processed = School.process_city_plus_area(user_input)

        # process dublin 1-24 in address, like Enniskerry Road, Sandyford, Dublin 18
        area_address = School.process_dublin_with_region_number(input_processed)
        input = area_address[1]

        #  process punctuation ，.
        input_split = School.process_punctuation(input)

        # make fuzzy query statement
        like = School.make_query_statement(input_split, area_address[0])

        return redirect(url_for('.result', like=like, coordination = geolocation))

    return render_template('main/home.html', form=form, current_location = current_location)


@main.route('/search/<input_keyword>', methods=['GET', 'POST'])
def search(input_keyword):
    """
    This function is used to convert the user input keyword to fuzzy query statement which is used to query database
    :param input_keyword: the keyword user input to search box
    :return: redirect to search result page
    """

    if not 'ireland' in input_keyword.lower():
        keyword = input_keyword + ' '+ 'Ireland'
    else:
        keyword = input_keyword

    # get input place's latitude and longitude
    signal = True
    count = 0
    while signal:
        input_coordination = User.get_coordination(keyword)
        count = count + 1
        if len(input_coordination) != 0 or count == 5:
            signal = False
            break
    if input_coordination != 'unknown' and len(input_coordination) != 0:
        geolocation = str(input_coordination[0]) + "," + str(input_coordination[1])
    else:
        geolocation = "search_location"

    # GET THE NUMBER IN STRING, process input keyword like Dublin1 and Dublin 1(has space and no space)
    # Fuzzy Query Statement should be like '%dublin% 1' which can match all schools in Dublin 1.
    user_input = input_keyword
    input_processed = School.process_city_plus_area(user_input)

    # process dublin 1-24 in address, like Enniskerry Road, Sandyford, Dublin 18
    area_address = School.process_dublin_with_region_number(input_processed)
    input = area_address[1]

    #  process punctuation ，.
    input_split = School.process_punctuation(input)

    # make fuzzy query statement
    like = School.make_query_statement(input_split, area_address[0])

    return redirect(url_for('.result', like=like, coordination = geolocation))


@main.route('/click_on_map/<coordination>/<city>', methods=['GET', 'POST'])
def click_on_map(coordination, city):

    """
    This route function is used for when users click on the map to relocate the position and compute the distance between map marker and schools
    :param coordination: the coordination of the place users click on the map
    :param city: the city of the place users click on the map
    :return: nearby school list(JSON)
    """
    join_search = db.session.query(School, Rank, Pro2017).outerjoin(Rank).outerjoin(Pro2017)

    lat = coordination.split(',')[0]
    lng = coordination.split(',')[1]

    school_list = join_search.filter(School.county == city)
    result_list = []
    for school in school_list:
        distance_computing1 = School.distance_calculator(float(school[0].lat), float(school[0].lng),
                                                         float(lat), float(lng))
        if distance_computing1 < 20:
            school = list(school)
            school[0].distance = round(distance_computing1, 2)
            result_list.append(school)
    result_list.sort(key=lambda x: x[0].distance)

    data = School.make_json(result_list)

    return jsonify({'result': data})


@main.route('/result/<like>/<coordination>')
def result(like, coordination):
    """
    The functions is used to query database
    :param like: fuzzy query statement
    :param coordination: the coordination of the place user input
    :return: render the search result page
    """

    keyword = like.replace('%', ' ')

    # generate the url
    url = url_for('auth.login', type='result' + ',' + like)
    like = like.lower()

    global current_location
    if current_location is None:
        current_location = [53.3083, -6.2236]

    global user_db
    if user_db is None:
        join_search = db.session.query(School, Rank, Pro2017).outerjoin(Rank).outerjoin(Pro2017)
    else:
        join_search = user_db

    counties = ['antrim', 'armagh', 'carlow', 'cavan', 'clare', 'cork', 'derry', 'donegal', 'down', 'dublin',
                'fermanagh', 'galway', 'kerry', 'kildare', 'kilkenny', 'laois', 'leitrim', 'limerick',
                'Longford', 'Louth', 'Mayo', 'Meath', 'Monaghan', 'Offaly', 'Roscommon',
                'sligo', 'tipperary', 'tyrone', 'waterford', 'westmeath', 'wexford', 'wicklow']

    # check whether input_keyword includes above conties
    intersection_with_counties = list(set(like.split('%')) & set(counties))

    # try to match the record in database - match with address and school name
    # records can be matched in database
    if len(intersection_with_counties) != 0:
        new_like2 = like.replace('%' + intersection_with_counties[0] + '%', '')
        result1 = join_search.filter(School.address.ilike('%' + intersection_with_counties[0] + '%' + new_like2)).all()
        if len(result1) == 0:
            result1 = join_search.filter(School.address.ilike(new_like2 + '%' + intersection_with_counties[0] + '%')).all()
        if len(result1) == 0:
            result1 = join_search.filter(School.address.ilike(new_like2)).all()
        result2 = join_search.filter(School.official_school_name.ilike(new_like2),
                                     School.county.like('%' + intersection_with_counties[0] + '%')).all()
    else:
        # Dublin 4

Code/app/templates/main/home.html
<!DOCTYPE html>

<!--[if lt IE 7]>
<html class="no-bootstrap lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-bootstrap lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-bootstrap lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
{% import "bootstrap/wtf.html" as wtf %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Home</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Main Style Sheet-->
    <link rel="stylesheet" href="../../static/css/bootstrap3/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/bootstrap3/bootstrap-theme.css">
    <link rel="stylesheet" href="../../static/css/home.css">

    <!-- Main JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="../../static/js/bootstrap3/bootstrap.js"></script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAGOu1MCWVAvOQ24l6-tOdRpXgKXEDWvYs&language=en&libraries=places">
    </script>
    <script src="../../static/js/pagination/jquery.twbsPagination.js"></script>
    <script src="../../static/js/home.js"></script>

    <!-- Respond.bootstrap for IE 8 or less only -->
    <!--[if (lt IE 9) & (!IEMobile)]>
    <script src="bootstrap/vendor/respond.min.bootstrap"></script>
    <![endif]-->

</head>

<body class="products">
<!-- navigation bar -->
<header role="banner">
    <nav role="navigation" class="navbar navbar-static-top navbar-default" style="margin-bottom:0px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">
                    <img src="../../static/img/logo.png" alt="BestChoice'" width="120" style="margin-top:-9px">
                </a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-left">
                    <li class="active"><a href="{{ url_for('main.index') }}">
                        <span class="glyphicon glyphicon-home"></span> Home
                    </a></li>
                    <li><a href="{{ url_for('main.result', like='%Dublin%', coordination ='53.3498123,-6.2624488' )}}">
                        <span class="glyphicon glyphicon-search"></span> Search
                    </a></li>
                    <li><a href="{{ url_for('main.rank') }}">
                        <span class="glyphicon glyphicon-sort-by-order"></span> Rank
                    </a></li>
                    <li><a href="{{ url_for('operation.compare') }}">
                        <span class="glyphicon glyphicon-tasks"></span> Compare
                    </a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        {% if current_user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                {% if current_user.photo %}
                                    <img src="{{ current_user.photo }}" height="23" width="23">
                                {% else %}
                                    <img class="img-rounded profile-thumbnail"
                                         src="../../static/avatars/default_avatar.jpg" height="23"
                                         width="23">
                                {% endif %}
                                {{ current_user.username }} <b class="caret"></b>
                            </a>

                            <ul class="dropdown-menu">
                                {% if current_user.login_type != 'website' %}
                                    <li><a href="{{ url_for('operation.user', username=current_user.username) }}">Profile</a>
                                    </li>
                                    {#                                    <li><a href="{{ url_for('operation.following', username=current_user.username)}}">Watching List</a></li>#}
                                    <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
                                {% else %}
                                    <li><a href="{{ url_for('operation.user', username=current_user.username) }}">Profile</a>
                                    </li>
                                    {#                                    <li><a href="{{ url_for('operation.following', username=current_user.username)}}">Watching List</a></li>#}
                                    <li><a href="{{ url_for('operation.change_password') }}">Change password</a></li>
                                    <li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
                                {% endif %}
                            </ul>

                            </li>
                        {% else %}
                            <li><a href="{{ url_for('auth.login',type ="index") }}">Log In</a></li>
                        {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container -->
    </nav>
</header>

<!--[if lte IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to
    improve your experience.</p>
<![endif]-->


<main role="main">

    <!-- INTRO SECTION -->
    <section id="welcome" class="jumbotron">
        <div class="container">

            <div class="search-bar">
                <form role="form" method="post">
                    {{ form.hidden_tag() }}
                    {# {{ wtf.form_errors(fajax_getSchoolDataByLatlngorm, hiddens="only") }}#}


                    <div class="row">
                        <!--<div class="form-group rightLine col-lg-2 col-sm-2 col-md-2">
                            <input id="location" type="text" name="location" placeholder="Your City" value="Co.Dublin"
                                   readonly="readonly" >
                            <label for="location" class="location"><i class="fa fa-dot-circle-o"></i></label>
                        </div>-->
{#                        <div class="form-group rightLine col-lg-2  col-sm-2 col-md-2">#}
{#                            <div class="btn-group bootstrap-select listing-categories dropdown">#}
{#                                {{ wtf.form_field(form.select, class='form-control', id = "county") }}#}
{#                            </div>#}
{##}
{#                        </div>#}


                        <div class="form-group col-lg-10  col-sm-10 col-md-10">
                            {{ wtf.form_field(form.search, class='search-text', id = "omg") }}
                        </div>

                        <div class="form-group col-lg-2  col-sm-2 col-md-2">
                            {{ wtf.form_field(form.lat, class='search-text', id = "lat", type = "hidden", value="") }}
                            {{ wtf.form_field(form.lng, class='search-text', id = "lng", type = "hidden", value="") }}
{#                             <input type="hidden" name="lat" id="lat" value="">#}
{#                        <input type="hidden" name="lng" id="lng" value="">#}
                            <input type="submit" value="Search" class="submit">
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </section>


    <div class="container">

        <div class="page-header">
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
            <h4>Welcome to Best Choice</h4>
            <h4>{% if current_user.is_authenticated %} Hello, {{ current_user.username }}!{% endif %}</h4>
            <h1>Post-Primary Schools
                <small>Sorted by current distance by default</small>
            </h1>
        </div>

        <div class="row">
            <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-12">
                <div id="mapholder" class="grid-options" style="height: 400px">

                </div><!-- Google Map area -->

                <script>
                    $(function () {

                        initMap();//Execution function

                        //geocodeLocation(latlng);//locate the current count

                        $("#map").on("mouseover", ".marker-container", function () {
                            $(this).find(".detail-info").show();
                        });

                        $("#map").on("mouseout", ".marker-container", function () {
                            $(this).find(".detail-info").hide();
                        });
                    });
                </script>
                    <div class="col-sm-12 centre">
                        <span class="map-guide">Click on map to find your place <img src = '../../static/img/locate.png' height="45"width="45"> </span>
                    </div>
                    <div>
                        <span id="address" style="color: #00b3ee;font-family: 'microsoft yahei', Arial, sans-serif;"></span>
                    </div>
                </div>
            </div>
            </div>

            <div class="products-grid col-sm-8">
                <div id="loadgif" style="text-align: center; width: 100%;"> 　　
                    <img style="display: inline-block;width:200px; height:200px; top:50%; left:50%;" alt="loading..."
                         src="../../static/img/search/loader.gif"/>
                </div>

                <!-- school list-->
                <div id="school-holder" class="row">


                </div><!-- row-->

                <div class="row">

                    <div class="col-md-2"></div>

                    <div id="pagination-row" class="row pagination-wrap col-md-8 mypagination">
                        <nav  aria-label="Page navigation">
                            <ul class="pagination" id="pagination"></ul>
                        </nav>

                    </div><!-- /.row.pagination-wrap -->

                    <div class="col-md-2"></div>

                </div>

                <script>

                    var pos = {'lat':53.3498118, 'lng': -6.2711979};

                    ajax_getSchoolDataByLatlng(pos);

                </script>


            </div><!-- /.products-grid -->

        </div><!-- /.row -->
    </div><!-- /.container -->
</main>
<footer role="contentinfo">
    <div class="container">

        <p class="footer-brand"><a href="#"><img src="../../static/img/logo.png" width="80"
                                                          alt="Bootstrappin'"></a></p>

    </div><!-- /.container -->
</footer>


<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
    (function (d, t) {
        var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
        g.src = ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g, s)
    }(document, 'script'));
</script>

</body>
</html>